### ISSUE TITLE
secrets.ymlにtwitterのAPIキーがベタ書きされている

### ISSUE THREAD

**Issue by AnguillaJaponica** [willnet/awesome_events#6]
パーフェクトRuby on Railsを読むにあたり、参考にさせていただきました。ありがとうございます。

標記のとおりですが、問題はございませんか？(もし余計な心配でしたら、どうぞご放念くださいませ)

**Comment by willnet** [comment]
@AnguillaJaponica 

ご指摘ありがとうございます！(そして返事遅れてすみません)
このリポジトリ上で記載しているAPIキーは無効にしてあるので大丈夫です 😃

**Comment by AnguillaJaponica** [comment]
(出しゃばる感じでお騒がせいたしました。。)
何よりです！
